use_frameworks!
inhibit_all_warnings!

platform :ios, '13.0'

target 'Decele_Example' do
  pod 'Decele', :path => '../'

  target 'Decele_Tests' do
    inherit! :search_paths

  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "YES"
              config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13'
          end
      end
  end
end
