use_frameworks!
install! 'cocoapods', :warn_for_unused_master_specs_repo => false
inhibit_all_warnings!

platform :ios, '13.0'

abstract_target 'SharedPods' do
  pod 'R.swift', :git => 'https://github.com/MacKevinCE/R.swift.git', :commit => '1701d96'

  target 'ContactsDecele' do
    pod 'Decele/Contacts', :path => '../'

    target 'ContactsDeceleTests' do
    end
  end

  target 'Persistent' do
    pod 'Decele/Persistent', :path => '../'
    
    target 'PersistentTests' do
    end
  end

  target 'Crypto' do
    pod 'Decele/Crypto', :path => '../'
    
    target 'CryptoTests' do
    end
  end
  
  target 'Chuck' do
    pod 'Decele/Chuck', :path => '../'
    
    target 'ChuckTests' do
    end
  end
  
  target 'Repository' do
    pod 'Decele/Repository', :path => '../'
    
    target 'RepositoryTests' do
    end
  end

  target 'Components' do
    pod 'Decele/Components', :path => '../'
    
    target 'ComponentsTests' do
    end
  end

  target 'NameClass' do
    pod 'Decele/Components/NameClass', :path => '../'
    
    target 'NameClassTests' do
    end
  end

  target 'NibView' do
    pod 'Decele/Components/NibView', :path => '../'
    
    target 'NibViewTests' do
    end
  end

  target 'FloatingPanelDecele' do
    pod 'Decele/Components/FloatingPanel', :path => '../'
    
    target 'FloatingPanelDeceleTests' do
    end
  end

  target 'SideMenuDecele' do
    pod 'Decele/Components/SideMenu', :path => '../'
    
    target 'SideMenuDeceleTests' do
    end
  end

  target 'Button' do
    pod 'Decele/Components/Button', :path => '../'
    
    target 'ButtonTests' do
    end
  end

  target 'TextField' do
    pod 'Decele/Components/TextField', :path => '../'
    
    target 'TextFieldTests' do
    end
  end

  target 'Fonts' do
    pod 'Decele/Fonts', :path => '../'
    
    target 'FontsTests' do
    end
  end

  target 'CoreDecele' do
    pod 'Decele/Repository', :path => '../'
    pod 'Mocker', '~> 2.5.5'

    target 'CoreDeceleTests' do
    end
  end

  target 'All' do
    pod 'Decele', :path => '../'

    target 'AllTests' do
    end
  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "YES"
              config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13'
          end
      end
  end
end
