//
//  FontawesomeBrands.swift
//  Decele
//
//  Created by Mc Kevin on 25/06/23.
//
// MARK: - FontawesomeBrands
public enum FontawesomeBrands: String, FontName {
    case fab42Group = "fab-42-group"
    case fab500Px = "fab-500px"
    case fabAccessibleIcon = "fab-accessible-icon"
    case fabAccusoft = "fab-accusoft"
    case fabAdn = "fab-adn"
    case fabAdversal = "fab-adversal"
    case fabAffiliatetheme = "fab-affiliatetheme"
    case fabAirbnb = "fab-airbnb"
    case fabAlgolia = "fab-algolia"
    case fabAlipay = "fab-alipay"
    case fabAmazon = "fab-amazon"
    case fabAmazonPay = "fab-amazon-pay"
    case fabAmilia = "fab-amilia"
    case fabAndroid = "fab-android"
    case fabAngellist = "fab-angellist"
    case fabAngrycreative = "fab-angrycreative"
    case fabAngular = "fab-angular"
    case fabAppStore = "fab-app-store"
    case fabAppStoreIos = "fab-app-store-ios"
    case fabApper = "fab-apper"
    case fabApple = "fab-apple"
    case fabApplePay = "fab-apple-pay"
    case fabArtstation = "fab-artstation"
    case fabAsymmetrik = "fab-asymmetrik"
    case fabAtlassian = "fab-atlassian"
    case fabAudible = "fab-audible"
    case fabAutoprefixer = "fab-autoprefixer"
    case fabAvianex = "fab-avianex"
    case fabAviato = "fab-aviato"
    case fabAws = "fab-aws"
    case fabBandcamp = "fab-bandcamp"
    case fabBattleNet = "fab-battle-net"
    case fabBehance = "fab-behance"
    case fabBilibili = "fab-bilibili"
    case fabBimobject = "fab-bimobject"
    case fabBitbucket = "fab-bitbucket"
    case fabBitcoin = "fab-bitcoin"
    case fabBity = "fab-bity"
    case fabBlackTie = "fab-black-tie"
    case fabBlackberry = "fab-blackberry"
    case fabBlogger = "fab-blogger"
    case fabBloggerB = "fab-blogger-b"
    case fabBluetooth = "fab-bluetooth"
    case fabBluetoothB = "fab-bluetooth-b"
    case fabBootstrap = "fab-bootstrap"
    case fabBots = "fab-bots"
    case fabBtc = "fab-btc"
    case fabBuffer = "fab-buffer"
    case fabBuromobelexperte = "fab-buromobelexperte"
    case fabBuyNLarge = "fab-buy-n-large"
    case fabBuysellads = "fab-buysellads"
    case fabCanadianMapleLeaf = "fab-canadian-maple-leaf"
    case fabCcAmazonPay = "fab-cc-amazon-pay"
    case fabCcAmex = "fab-cc-amex"
    case fabCcApplePay = "fab-cc-apple-pay"
    case fabCcDinersClub = "fab-cc-diners-club"
    case fabCcDiscover = "fab-cc-discover"
    case fabCcJcb = "fab-cc-jcb"
    case fabCcMastercard = "fab-cc-mastercard"
    case fabCcPaypal = "fab-cc-paypal"
    case fabCcStripe = "fab-cc-stripe"
    case fabCcVisa = "fab-cc-visa"
    case fabCentercode = "fab-centercode"
    case fabCentos = "fab-centos"
    case fabChrome = "fab-chrome"
    case fabChromecast = "fab-chromecast"
    case fabCloudflare = "fab-cloudflare"
    case fabCloudscale = "fab-cloudscale"
    case fabCloudsmith = "fab-cloudsmith"
    case fabCloudversify = "fab-cloudversify"
    case fabCmplid = "fab-cmplid"
    case fabCodepen = "fab-codepen"
    case fabCodiepie = "fab-codiepie"
    case fabConfluence = "fab-confluence"
    case fabConnectdevelop = "fab-connectdevelop"
    case fabContao = "fab-contao"
    case fabCottonBureau = "fab-cotton-bureau"
    case fabCpanel = "fab-cpanel"
    case fabCreativeCommons = "fab-creative-commons"
    case fabCreativeCommonsBy = "fab-creative-commons-by"
    case fabCreativeCommonsNc = "fab-creative-commons-nc"
    case fabCreativeCommonsNcEu = "fab-creative-commons-nc-eu"
    case fabCreativeCommonsNcJp = "fab-creative-commons-nc-jp"
    case fabCreativeCommonsNd = "fab-creative-commons-nd"
    case fabCreativeCommonsPd = "fab-creative-commons-pd"
    case fabCreativeCommonsPdAlt = "fab-creative-commons-pd-alt"
    case fabCreativeCommonsRemix = "fab-creative-commons-remix"
    case fabCreativeCommonsSa = "fab-creative-commons-sa"
    case fabCreativeCommonsSampling = "fab-creative-commons-sampling"
    case fabCreativeCommonsSamplingPlus = "fab-creative-commons-sampling-plus"
    case fabCreativeCommonsShare = "fab-creative-commons-share"
    case fabCreativeCommonsZero = "fab-creative-commons-zero"
    case fabCriticalRole = "fab-critical-role"
    case fabCss3 = "fab-css3"
    case fabCss3Alt = "fab-css3-alt"
    case fabCuttlefish = "fab-cuttlefish"
    case fabDAndD = "fab-d-and-d"
    case fabDAndDBeyond = "fab-d-and-d-beyond"
    case fabDailymotion = "fab-dailymotion"
    case fabDashcube = "fab-dashcube"
    case fabDeezer = "fab-deezer"
    case fabDelicious = "fab-delicious"
    case fabDeploydog = "fab-deploydog"
    case fabDeskpro = "fab-deskpro"
    case fabDev = "fab-dev"
    case fabDeviantart = "fab-deviantart"
    case fabDhl = "fab-dhl"
    case fabDiaspora = "fab-diaspora"
    case fabDigg = "fab-digg"
    case fabDigitalOcean = "fab-digital-ocean"
    case fabDiscord = "fab-discord"
    case fabDiscourse = "fab-discourse"
    case fabDochub = "fab-dochub"
    case fabDocker = "fab-docker"
    case fabDraft2Digital = "fab-draft2digital"
    case fabDribbble = "fab-dribbble"
    case fabDropbox = "fab-dropbox"
    case fabDrupal = "fab-drupal"
    case fabDyalog = "fab-dyalog"
    case fabEarlybirds = "fab-earlybirds"
    case fabEbay = "fab-ebay"
    case fabEdge = "fab-edge"
    case fabEdgeLegacy = "fab-edge-legacy"
    case fabElementor = "fab-elementor"
    case fabEllo = "fab-ello"
    case fabEmber = "fab-ember"
    case fabEmpire = "fab-empire"
    case fabEnvira = "fab-envira"
    case fabErlang = "fab-erlang"
    case fabEthereum = "fab-ethereum"
    case fabEtsy = "fab-etsy"
    case fabEvernote = "fab-evernote"
    case fabExpeditedssl = "fab-expeditedssl"
    case fabFacebook = "fab-facebook"
    case fabFacebookF = "fab-facebook-f"
    case fabFacebookMessenger = "fab-facebook-messenger"
    case fabFantasyFlightGames = "fab-fantasy-flight-games"
    case fabFedex = "fab-fedex"
    case fabFedora = "fab-fedora"
    case fabFigma = "fab-figma"
    case fabFirefox = "fab-firefox"
    case fabFirefoxBrowser = "fab-firefox-browser"
    case fabFirstOrder = "fab-first-order"
    case fabFirstOrderAlt = "fab-first-order-alt"
    case fabFirstdraft = "fab-firstdraft"
    case fabFlickr = "fab-flickr"
    case fabFlipboard = "fab-flipboard"
    case fabFly = "fab-fly"
    case fabFontAwesome = "fab-font-awesome"
    case fabFonticons = "fab-fonticons"
    case fabFonticonsFi = "fab-fonticons-fi"
    case fabFortAwesome = "fab-fort-awesome"
    case fabFortAwesomeAlt = "fab-fort-awesome-alt"
    case fabForumbee = "fab-forumbee"
    case fabFoursquare = "fab-foursquare"
    case fabFreeCodeCamp = "fab-free-code-camp"
    case fabFreebsd = "fab-freebsd"
    case fabFulcrum = "fab-fulcrum"
    case fabGalacticRepublic = "fab-galactic-republic"
    case fabGalacticSenate = "fab-galactic-senate"
    case fabGetPocket = "fab-get-pocket"
    case fabGg = "fab-gg"
    case fabGgCircle = "fab-gg-circle"
    case fabGit = "fab-git"
    case fabGitAlt = "fab-git-alt"
    case fabGithub = "fab-github"
    case fabGithubAlt = "fab-github-alt"
    case fabGitkraken = "fab-gitkraken"
    case fabGitlab = "fab-gitlab"
    case fabGitter = "fab-gitter"
    case fabGlide = "fab-glide"
    case fabGlideG = "fab-glide-g"
    case fabGofore = "fab-gofore"
    case fabGolang = "fab-golang"
    case fabGoodreads = "fab-goodreads"
    case fabGoodreadsG = "fab-goodreads-g"
    case fabGoogle = "fab-google"
    case fabGoogleDrive = "fab-google-drive"
    case fabGooglePay = "fab-google-pay"
    case fabGooglePlay = "fab-google-play"
    case fabGooglePlus = "fab-google-plus"
    case fabGooglePlusG = "fab-google-plus-g"
    case fabGoogleWallet = "fab-google-wallet"
    case fabGratipay = "fab-gratipay"
    case fabGrav = "fab-grav"
    case fabGripfire = "fab-gripfire"
    case fabGrunt = "fab-grunt"
    case fabGuilded = "fab-guilded"
    case fabGulp = "fab-gulp"
    case fabHackerNews = "fab-hacker-news"
    case fabHackerrank = "fab-hackerrank"
    case fabHashnode = "fab-hashnode"
    case fabHips = "fab-hips"
    case fabHireAHelper = "fab-hire-a-helper"
    case fabHive = "fab-hive"
    case fabHooli = "fab-hooli"
    case fabHornbill = "fab-hornbill"
    case fabHotjar = "fab-hotjar"
    case fabHouzz = "fab-houzz"
    case fabHtml5 = "fab-html5"
    case fabHubspot = "fab-hubspot"
    case fabIdeal = "fab-ideal"
    case fabImdb = "fab-imdb"
    case fabInstagram = "fab-instagram"
    case fabInstalod = "fab-instalod"
    case fabIntercom = "fab-intercom"
    case fabInternetExplorer = "fab-internet-explorer"
    case fabInvision = "fab-invision"
    case fabIoxhost = "fab-ioxhost"
    case fabItchIo = "fab-itch-io"
    case fabItunes = "fab-itunes"
    case fabItunesNote = "fab-itunes-note"
    case fabJava = "fab-java"
    case fabJediOrder = "fab-jedi-order"
    case fabJenkins = "fab-jenkins"
    case fabJira = "fab-jira"
    case fabJoget = "fab-joget"
    case fabJoomla = "fab-joomla"
    case fabJs = "fab-js"
    case fabJsfiddle = "fab-jsfiddle"
    case fabKaggle = "fab-kaggle"
    case fabKeybase = "fab-keybase"
    case fabKeycdn = "fab-keycdn"
    case fabKickstarter = "fab-kickstarter"
    case fabKickstarterK = "fab-kickstarter-k"
    case fabKorvue = "fab-korvue"
    case fabLaravel = "fab-laravel"
    case fabLastfm = "fab-lastfm"
    case fabLeanpub = "fab-leanpub"
    case fabLess = "fab-less"
    case fabLine = "fab-line"
    case fabLinkedin = "fab-linkedin"
    case fabLinkedinIn = "fab-linkedin-in"
    case fabLinode = "fab-linode"
    case fabLinux = "fab-linux"
    case fabLyft = "fab-lyft"
    case fabMagento = "fab-magento"
    case fabMailchimp = "fab-mailchimp"
    case fabMandalorian = "fab-mandalorian"
    case fabMarkdown = "fab-markdown"
    case fabMastodon = "fab-mastodon"
    case fabMaxcdn = "fab-maxcdn"
    case fabMdb = "fab-mdb"
    case fabMedapps = "fab-medapps"
    case fabMedium = "fab-medium"
    case fabMedrt = "fab-medrt"
    case fabMeetup = "fab-meetup"
    case fabMegaport = "fab-megaport"
    case fabMendeley = "fab-mendeley"
    case fabMeta = "fab-meta"
    case fabMicroblog = "fab-microblog"
    case fabMicrosoft = "fab-microsoft"
    case fabMix = "fab-mix"
    case fabMixcloud = "fab-mixcloud"
    case fabMixer = "fab-mixer"
    case fabMizuni = "fab-mizuni"
    case fabModx = "fab-modx"
    case fabMonero = "fab-monero"
    case fabNapster = "fab-napster"
    case fabNeos = "fab-neos"
    case fabNfcDirectional = "fab-nfc-directional"
    case fabNfcSymbol = "fab-nfc-symbol"
    case fabNimblr = "fab-nimblr"
    case fabNode = "fab-node"
    case fabNodeJs = "fab-node-js"
    case fabNpm = "fab-npm"
    case fabNs8 = "fab-ns8"
    case fabNutritionix = "fab-nutritionix"
    case fabOctopusDeploy = "fab-octopus-deploy"
    case fabOdnoklassniki = "fab-odnoklassniki"
    case fabOdysee = "fab-odysee"
    case fabOldRepublic = "fab-old-republic"
    case fabOpencart = "fab-opencart"
    case fabOpenid = "fab-openid"
    case fabOpera = "fab-opera"
    case fabOptinMonster = "fab-optin-monster"
    case fabOrcid = "fab-orcid"
    case fabOsi = "fab-osi"
    case fabPadlet = "fab-padlet"
    case fabPage4 = "fab-page4"
    case fabPagelines = "fab-pagelines"
    case fabPalfed = "fab-palfed"
    case fabPatreon = "fab-patreon"
    case fabPaypal = "fab-paypal"
    case fabPerbyte = "fab-perbyte"
    case fabPeriscope = "fab-periscope"
    case fabPhabricator = "fab-phabricator"
    case fabPhoenixFramework = "fab-phoenix-framework"
    case fabPhoenixSquadron = "fab-phoenix-squadron"
    case fabPhp = "fab-php"
    case fabPiedPiper = "fab-pied-piper"
    case fabPiedPiperAlt = "fab-pied-piper-alt"
    case fabPiedPiperHat = "fab-pied-piper-hat"
    case fabPiedPiperPp = "fab-pied-piper-pp"
    case fabPinterest = "fab-pinterest"
    case fabPinterestP = "fab-pinterest-p"
    case fabPix = "fab-pix"
    case fabPlaystation = "fab-playstation"
    case fabProductHunt = "fab-product-hunt"
    case fabPushed = "fab-pushed"
    case fabPython = "fab-python"
    case fabQq = "fab-qq"
    case fabQuinscape = "fab-quinscape"
    case fabQuora = "fab-quora"
    case fabRProject = "fab-r-project"
    case fabRaspberryPi = "fab-raspberry-pi"
    case fabRavelry = "fab-ravelry"
    case fabReact = "fab-react"
    case fabReacteurope = "fab-reacteurope"
    case fabReadme = "fab-readme"
    case fabRebel = "fab-rebel"
    case fabRedRiver = "fab-red-river"
    case fabReddit = "fab-reddit"
    case fabRedditAlien = "fab-reddit-alien"
    case fabRedhat = "fab-redhat"
    case fabRenren = "fab-renren"
    case fabReplyd = "fab-replyd"
    case fabResearchgate = "fab-researchgate"
    case fabResolving = "fab-resolving"
    case fabRev = "fab-rev"
    case fabRocketchat = "fab-rocketchat"
    case fabRockrms = "fab-rockrms"
    case fabRust = "fab-rust"
    case fabSafari = "fab-safari"
    case fabSalesforce = "fab-salesforce"
    case fabSass = "fab-sass"
    case fabSchlix = "fab-schlix"
    case fabScreenpal = "fab-screenpal"
    case fabScribd = "fab-scribd"
    case fabSearchengin = "fab-searchengin"
    case fabSellcast = "fab-sellcast"
    case fabSellsy = "fab-sellsy"
    case fabServicestack = "fab-servicestack"
    case fabShirtsinbulk = "fab-shirtsinbulk"
    case fabShopify = "fab-shopify"
    case fabShopware = "fab-shopware"
    case fabSimplybuilt = "fab-simplybuilt"
    case fabSistrix = "fab-sistrix"
    case fabSith = "fab-sith"
    case fabSitrox = "fab-sitrox"
    case fabSketch = "fab-sketch"
    case fabSkyatlas = "fab-skyatlas"
    case fabSkype = "fab-skype"
    case fabSlack = "fab-slack"
    case fabSlideshare = "fab-slideshare"
    case fabSnapchat = "fab-snapchat"
    case fabSoundcloud = "fab-soundcloud"
    case fabSourcetree = "fab-sourcetree"
    case fabSpaceAwesome = "fab-space-awesome"
    case fabSpeakap = "fab-speakap"
    case fabSpeakerDeck = "fab-speaker-deck"
    case fabSpotify = "fab-spotify"
    case fabSquareBehance = "fab-square-behance"
    case fabSquareDribbble = "fab-square-dribbble"
    case fabSquareFacebook = "fab-square-facebook"
    case fabSquareFontAwesome = "fab-square-font-awesome"
    case fabSquareFontAwesomeStroke = "fab-square-font-awesome-stroke"
    case fabSquareGit = "fab-square-git"
    case fabSquareGithub = "fab-square-github"
    case fabSquareGitlab = "fab-square-gitlab"
    case fabSquareGooglePlus = "fab-square-google-plus"
    case fabSquareHackerNews = "fab-square-hacker-news"
    case fabSquareInstagram = "fab-square-instagram"
    case fabSquareJs = "fab-square-js"
    case fabSquareLastfm = "fab-square-lastfm"
    case fabSquareOdnoklassniki = "fab-square-odnoklassniki"
    case fabSquarePiedPiper = "fab-square-pied-piper"
    case fabSquarePinterest = "fab-square-pinterest"
    case fabSquareReddit = "fab-square-reddit"
    case fabSquareSnapchat = "fab-square-snapchat"
    case fabSquareSteam = "fab-square-steam"
    case fabSquareTumblr = "fab-square-tumblr"
    case fabSquareTwitter = "fab-square-twitter"
    case fabSquareViadeo = "fab-square-viadeo"
    case fabSquareVimeo = "fab-square-vimeo"
    case fabSquareWhatsapp = "fab-square-whatsapp"
    case fabSquareXing = "fab-square-xing"
    case fabSquareYoutube = "fab-square-youtube"
    case fabSquarespace = "fab-squarespace"
    case fabStackExchange = "fab-stack-exchange"
    case fabStackOverflow = "fab-stack-overflow"
    case fabStackpath = "fab-stackpath"
    case fabStaylinked = "fab-staylinked"
    case fabSteam = "fab-steam"
    case fabSteamSymbol = "fab-steam-symbol"
    case fabStickerMule = "fab-sticker-mule"
    case fabStrava = "fab-strava"
    case fabStripe = "fab-stripe"
    case fabStripeS = "fab-stripe-s"
    case fabStubber = "fab-stubber"
    case fabStudiovinari = "fab-studiovinari"
    case fabStumbleupon = "fab-stumbleupon"
    case fabStumbleuponCircle = "fab-stumbleupon-circle"
    case fabSuperpowers = "fab-superpowers"
    case fabSupple = "fab-supple"
    case fabSuse = "fab-suse"
    case fabSwift = "fab-swift"
    case fabSymfony = "fab-symfony"
    case fabTeamspeak = "fab-teamspeak"
    case fabTelegram = "fab-telegram"
    case fabTencentWeibo = "fab-tencent-weibo"
    case fabTheRedYeti = "fab-the-red-yeti"
    case fabThemeco = "fab-themeco"
    case fabThemeisle = "fab-themeisle"
    case fabThinkPeaks = "fab-think-peaks"
    case fabTiktok = "fab-tiktok"
    case fabTradeFederation = "fab-trade-federation"
    case fabTrello = "fab-trello"
    case fabTumblr = "fab-tumblr"
    case fabTwitch = "fab-twitch"
    case fabTwitter = "fab-twitter"
    case fabTypo3 = "fab-typo3"
    case fabUber = "fab-uber"
    case fabUbuntu = "fab-ubuntu"
    case fabUikit = "fab-uikit"
    case fabUmbraco = "fab-umbraco"
    case fabUncharted = "fab-uncharted"
    case fabUniregistry = "fab-uniregistry"
    case fabUnity = "fab-unity"
    case fabUnsplash = "fab-unsplash"
    case fabUntappd = "fab-untappd"
    case fabUps = "fab-ups"
    case fabUsb = "fab-usb"
    case fabUsps = "fab-usps"
    case fabUssunnah = "fab-ussunnah"
    case fabVaadin = "fab-vaadin"
    case fabViacoin = "fab-viacoin"
    case fabViadeo = "fab-viadeo"
    case fabViber = "fab-viber"
    case fabVimeo = "fab-vimeo"
    case fabVimeoV = "fab-vimeo-v"
    case fabVine = "fab-vine"
    case fabVk = "fab-vk"
    case fabVnv = "fab-vnv"
    case fabVuejs = "fab-vuejs"
    case fabWatchmanMonitoring = "fab-watchman-monitoring"
    case fabWaze = "fab-waze"
    case fabWeebly = "fab-weebly"
    case fabWeibo = "fab-weibo"
    case fabWeixin = "fab-weixin"
    case fabWhatsapp = "fab-whatsapp"
    case fabWhmcs = "fab-whmcs"
    case fabWikipediaW = "fab-wikipedia-w"
    case fabWindows = "fab-windows"
    case fabWirsindhandwerk = "fab-wirsindhandwerk"
    case fabWix = "fab-wix"
    case fabWizardsOfTheCoast = "fab-wizards-of-the-coast"
    case fabWodu = "fab-wodu"
    case fabWolfPackBattalion = "fab-wolf-pack-battalion"
    case fabWordpress = "fab-wordpress"
    case fabWordpressSimple = "fab-wordpress-simple"
    case fabWpbeginner = "fab-wpbeginner"
    case fabWpexplorer = "fab-wpexplorer"
    case fabWpforms = "fab-wpforms"
    case fabWpressr = "fab-wpressr"
    case fabXbox = "fab-xbox"
    case fabXing = "fab-xing"
    case fabYCombinator = "fab-y-combinator"
    case fabYahoo = "fab-yahoo"
    case fabYammer = "fab-yammer"
    case fabYandex = "fab-yandex"
    case fabYandexInternational = "fab-yandex-international"
    case fabYarn = "fab-yarn"
    case fabYelp = "fab-yelp"
    case fabYoast = "fab-yoast"
    case fabYoutube = "fab-youtube"
    case fabZhihu = "fab-zhihu"

    public var unicode: String {
        switch self {
            case .fab42Group: return "\u{e080}"
            case .fab500Px: return "\u{f26e}"
            case .fabAccessibleIcon: return "\u{f368}"
            case .fabAccusoft: return "\u{f369}"
            case .fabAdn: return "\u{f170}"
            case .fabAdversal: return "\u{f36a}"
            case .fabAffiliatetheme: return "\u{f36b}"
            case .fabAirbnb: return "\u{f834}"
            case .fabAlgolia: return "\u{f36c}"
            case .fabAlipay: return "\u{f642}"
            case .fabAmazon: return "\u{f270}"
            case .fabAmazonPay: return "\u{f42c}"
            case .fabAmilia: return "\u{f36d}"
            case .fabAndroid: return "\u{f17b}"
            case .fabAngellist: return "\u{f209}"
            case .fabAngrycreative: return "\u{f36e}"
            case .fabAngular: return "\u{f420}"
            case .fabAppStore: return "\u{f36f}"
            case .fabAppStoreIos: return "\u{f370}"
            case .fabApper: return "\u{f371}"
            case .fabApple: return "\u{f179}"
            case .fabApplePay: return "\u{f415}"
            case .fabArtstation: return "\u{f77a}"
            case .fabAsymmetrik: return "\u{f372}"
            case .fabAtlassian: return "\u{f77b}"
            case .fabAudible: return "\u{f373}"
            case .fabAutoprefixer: return "\u{f41c}"
            case .fabAvianex: return "\u{f374}"
            case .fabAviato: return "\u{f421}"
            case .fabAws: return "\u{f375}"
            case .fabBandcamp: return "\u{f2d5}"
            case .fabBattleNet: return "\u{f835}"
            case .fabBehance: return "\u{f1b4}"
            case .fabBilibili: return "\u{e3d9}"
            case .fabBimobject: return "\u{f378}"
            case .fabBitbucket: return "\u{f171}"
            case .fabBitcoin: return "\u{f379}"
            case .fabBity: return "\u{f37a}"
            case .fabBlackTie: return "\u{f27e}"
            case .fabBlackberry: return "\u{f37b}"
            case .fabBlogger: return "\u{f37c}"
            case .fabBloggerB: return "\u{f37d}"
            case .fabBluetooth: return "\u{f293}"
            case .fabBluetoothB: return "\u{f294}"
            case .fabBootstrap: return "\u{f836}"
            case .fabBots: return "\u{e340}"
            case .fabBtc: return "\u{f15a}"
            case .fabBuffer: return "\u{f837}"
            case .fabBuromobelexperte: return "\u{f37f}"
            case .fabBuyNLarge: return "\u{f8a6}"
            case .fabBuysellads: return "\u{f20d}"
            case .fabCanadianMapleLeaf: return "\u{f785}"
            case .fabCcAmazonPay: return "\u{f42d}"
            case .fabCcAmex: return "\u{f1f3}"
            case .fabCcApplePay: return "\u{f416}"
            case .fabCcDinersClub: return "\u{f24c}"
            case .fabCcDiscover: return "\u{f1f2}"
            case .fabCcJcb: return "\u{f24b}"
            case .fabCcMastercard: return "\u{f1f1}"
            case .fabCcPaypal: return "\u{f1f4}"
            case .fabCcStripe: return "\u{f1f5}"
            case .fabCcVisa: return "\u{f1f0}"
            case .fabCentercode: return "\u{f380}"
            case .fabCentos: return "\u{f789}"
            case .fabChrome: return "\u{f268}"
            case .fabChromecast: return "\u{f838}"
            case .fabCloudflare: return "\u{e07d}"
            case .fabCloudscale: return "\u{f383}"
            case .fabCloudsmith: return "\u{f384}"
            case .fabCloudversify: return "\u{f385}"
            case .fabCmplid: return "\u{e360}"
            case .fabCodepen: return "\u{f1cb}"
            case .fabCodiepie: return "\u{f284}"
            case .fabConfluence: return "\u{f78d}"
            case .fabConnectdevelop: return "\u{f20e}"
            case .fabContao: return "\u{f26d}"
            case .fabCottonBureau: return "\u{f89e}"
            case .fabCpanel: return "\u{f388}"
            case .fabCreativeCommons: return "\u{f25e}"
            case .fabCreativeCommonsBy: return "\u{f4e7}"
            case .fabCreativeCommonsNc: return "\u{f4e8}"
            case .fabCreativeCommonsNcEu: return "\u{f4e9}"
            case .fabCreativeCommonsNcJp: return "\u{f4ea}"
            case .fabCreativeCommonsNd: return "\u{f4eb}"
            case .fabCreativeCommonsPd: return "\u{f4ec}"
            case .fabCreativeCommonsPdAlt: return "\u{f4ed}"
            case .fabCreativeCommonsRemix: return "\u{f4ee}"
            case .fabCreativeCommonsSa: return "\u{f4ef}"
            case .fabCreativeCommonsSampling: return "\u{f4f0}"
            case .fabCreativeCommonsSamplingPlus: return "\u{f4f1}"
            case .fabCreativeCommonsShare: return "\u{f4f2}"
            case .fabCreativeCommonsZero: return "\u{f4f3}"
            case .fabCriticalRole: return "\u{f6c9}"
            case .fabCss3: return "\u{f13c}"
            case .fabCss3Alt: return "\u{f38b}"
            case .fabCuttlefish: return "\u{f38c}"
            case .fabDAndD: return "\u{f38d}"
            case .fabDAndDBeyond: return "\u{f6ca}"
            case .fabDailymotion: return "\u{e052}"
            case .fabDashcube: return "\u{f210}"
            case .fabDeezer: return "\u{e077}"
            case .fabDelicious: return "\u{f1a5}"
            case .fabDeploydog: return "\u{f38e}"
            case .fabDeskpro: return "\u{f38f}"
            case .fabDev: return "\u{f6cc}"
            case .fabDeviantart: return "\u{f1bd}"
            case .fabDhl: return "\u{f790}"
            case .fabDiaspora: return "\u{f791}"
            case .fabDigg: return "\u{f1a6}"
            case .fabDigitalOcean: return "\u{f391}"
            case .fabDiscord: return "\u{f392}"
            case .fabDiscourse: return "\u{f393}"
            case .fabDochub: return "\u{f394}"
            case .fabDocker: return "\u{f395}"
            case .fabDraft2Digital: return "\u{f396}"
            case .fabDribbble: return "\u{f17d}"
            case .fabDropbox: return "\u{f16b}"
            case .fabDrupal: return "\u{f1a9}"
            case .fabDyalog: return "\u{f399}"
            case .fabEarlybirds: return "\u{f39a}"
            case .fabEbay: return "\u{f4f4}"
            case .fabEdge: return "\u{f282}"
            case .fabEdgeLegacy: return "\u{e078}"
            case .fabElementor: return "\u{f430}"
            case .fabEllo: return "\u{f5f1}"
            case .fabEmber: return "\u{f423}"
            case .fabEmpire: return "\u{f1d1}"
            case .fabEnvira: return "\u{f299}"
            case .fabErlang: return "\u{f39d}"
            case .fabEthereum: return "\u{f42e}"
            case .fabEtsy: return "\u{f2d7}"
            case .fabEvernote: return "\u{f839}"
            case .fabExpeditedssl: return "\u{f23e}"
            case .fabFacebook: return "\u{f09a}"
            case .fabFacebookF: return "\u{f39e}"
            case .fabFacebookMessenger: return "\u{f39f}"
            case .fabFantasyFlightGames: return "\u{f6dc}"
            case .fabFedex: return "\u{f797}"
            case .fabFedora: return "\u{f798}"
            case .fabFigma: return "\u{f799}"
            case .fabFirefox: return "\u{f269}"
            case .fabFirefoxBrowser: return "\u{e007}"
            case .fabFirstOrder: return "\u{f2b0}"
            case .fabFirstOrderAlt: return "\u{f50a}"
            case .fabFirstdraft: return "\u{f3a1}"
            case .fabFlickr: return "\u{f16e}"
            case .fabFlipboard: return "\u{f44d}"
            case .fabFly: return "\u{f417}"
            case .fabFontAwesome: return "\u{f2b4}"
            case .fabFonticons: return "\u{f280}"
            case .fabFonticonsFi: return "\u{f3a2}"
            case .fabFortAwesome: return "\u{f286}"
            case .fabFortAwesomeAlt: return "\u{f3a3}"
            case .fabForumbee: return "\u{f211}"
            case .fabFoursquare: return "\u{f180}"
            case .fabFreeCodeCamp: return "\u{f2c5}"
            case .fabFreebsd: return "\u{f3a4}"
            case .fabFulcrum: return "\u{f50b}"
            case .fabGalacticRepublic: return "\u{f50c}"
            case .fabGalacticSenate: return "\u{f50d}"
            case .fabGetPocket: return "\u{f265}"
            case .fabGg: return "\u{f260}"
            case .fabGgCircle: return "\u{f261}"
            case .fabGit: return "\u{f1d3}"
            case .fabGitAlt: return "\u{f841}"
            case .fabGithub: return "\u{f09b}"
            case .fabGithubAlt: return "\u{f113}"
            case .fabGitkraken: return "\u{f3a6}"
            case .fabGitlab: return "\u{f296}"
            case .fabGitter: return "\u{f426}"
            case .fabGlide: return "\u{f2a5}"
            case .fabGlideG: return "\u{f2a6}"
            case .fabGofore: return "\u{f3a7}"
            case .fabGolang: return "\u{e40f}"
            case .fabGoodreads: return "\u{f3a8}"
            case .fabGoodreadsG: return "\u{f3a9}"
            case .fabGoogle: return "\u{f1a0}"
            case .fabGoogleDrive: return "\u{f3aa}"
            case .fabGooglePay: return "\u{e079}"
            case .fabGooglePlay: return "\u{f3ab}"
            case .fabGooglePlus: return "\u{f2b3}"
            case .fabGooglePlusG: return "\u{f0d5}"
            case .fabGoogleWallet: return "\u{f1ee}"
            case .fabGratipay: return "\u{f184}"
            case .fabGrav: return "\u{f2d6}"
            case .fabGripfire: return "\u{f3ac}"
            case .fabGrunt: return "\u{f3ad}"
            case .fabGuilded: return "\u{e07e}"
            case .fabGulp: return "\u{f3ae}"
            case .fabHackerNews: return "\u{f1d4}"
            case .fabHackerrank: return "\u{f5f7}"
            case .fabHashnode: return "\u{e499}"
            case .fabHips: return "\u{f452}"
            case .fabHireAHelper: return "\u{f3b0}"
            case .fabHive: return "\u{e07f}"
            case .fabHooli: return "\u{f427}"
            case .fabHornbill: return "\u{f592}"
            case .fabHotjar: return "\u{f3b1}"
            case .fabHouzz: return "\u{f27c}"
            case .fabHtml5: return "\u{f13b}"
            case .fabHubspot: return "\u{f3b2}"
            case .fabIdeal: return "\u{e013}"
            case .fabImdb: return "\u{f2d8}"
            case .fabInstagram: return "\u{f16d}"
            case .fabInstalod: return "\u{e081}"
            case .fabIntercom: return "\u{f7af}"
            case .fabInternetExplorer: return "\u{f26b}"
            case .fabInvision: return "\u{f7b0}"
            case .fabIoxhost: return "\u{f208}"
            case .fabItchIo: return "\u{f83a}"
            case .fabItunes: return "\u{f3b4}"
            case .fabItunesNote: return "\u{f3b5}"
            case .fabJava: return "\u{f4e4}"
            case .fabJediOrder: return "\u{f50e}"
            case .fabJenkins: return "\u{f3b6}"
            case .fabJira: return "\u{f7b1}"
            case .fabJoget: return "\u{f3b7}"
            case .fabJoomla: return "\u{f1aa}"
            case .fabJs: return "\u{f3b8}"
            case .fabJsfiddle: return "\u{f1cc}"
            case .fabKaggle: return "\u{f5fa}"
            case .fabKeybase: return "\u{f4f5}"
            case .fabKeycdn: return "\u{f3ba}"
            case .fabKickstarter: return "\u{f3bb}"
            case .fabKickstarterK: return "\u{f3bc}"
            case .fabKorvue: return "\u{f42f}"
            case .fabLaravel: return "\u{f3bd}"
            case .fabLastfm: return "\u{f202}"
            case .fabLeanpub: return "\u{f212}"
            case .fabLess: return "\u{f41d}"
            case .fabLine: return "\u{f3c0}"
            case .fabLinkedin: return "\u{f08c}"
            case .fabLinkedinIn: return "\u{f0e1}"
            case .fabLinode: return "\u{f2b8}"
            case .fabLinux: return "\u{f17c}"
            case .fabLyft: return "\u{f3c3}"
            case .fabMagento: return "\u{f3c4}"
            case .fabMailchimp: return "\u{f59e}"
            case .fabMandalorian: return "\u{f50f}"
            case .fabMarkdown: return "\u{f60f}"
            case .fabMastodon: return "\u{f4f6}"
            case .fabMaxcdn: return "\u{f136}"
            case .fabMdb: return "\u{f8ca}"
            case .fabMedapps: return "\u{f3c6}"
            case .fabMedium: return "\u{f23a}"
            case .fabMedrt: return "\u{f3c8}"
            case .fabMeetup: return "\u{f2e0}"
            case .fabMegaport: return "\u{f5a3}"
            case .fabMendeley: return "\u{f7b3}"
            case .fabMeta: return "\u{e49b}"
            case .fabMicroblog: return "\u{e01a}"
            case .fabMicrosoft: return "\u{f3ca}"
            case .fabMix: return "\u{f3cb}"
            case .fabMixcloud: return "\u{f289}"
            case .fabMixer: return "\u{e056}"
            case .fabMizuni: return "\u{f3cc}"
            case .fabModx: return "\u{f285}"
            case .fabMonero: return "\u{f3d0}"
            case .fabNapster: return "\u{f3d2}"
            case .fabNeos: return "\u{f612}"
            case .fabNfcDirectional: return "\u{e530}"
            case .fabNfcSymbol: return "\u{e531}"
            case .fabNimblr: return "\u{f5a8}"
            case .fabNode: return "\u{f419}"
            case .fabNodeJs: return "\u{f3d3}"
            case .fabNpm: return "\u{f3d4}"
            case .fabNs8: return "\u{f3d5}"
            case .fabNutritionix: return "\u{f3d6}"
            case .fabOctopusDeploy: return "\u{e082}"
            case .fabOdnoklassniki: return "\u{f263}"
            case .fabOdysee: return "\u{e5c6}"
            case .fabOldRepublic: return "\u{f510}"
            case .fabOpencart: return "\u{f23d}"
            case .fabOpenid: return "\u{f19b}"
            case .fabOpera: return "\u{f26a}"
            case .fabOptinMonster: return "\u{f23c}"
            case .fabOrcid: return "\u{f8d2}"
            case .fabOsi: return "\u{f41a}"
            case .fabPadlet: return "\u{e4a0}"
            case .fabPage4: return "\u{f3d7}"
            case .fabPagelines: return "\u{f18c}"
            case .fabPalfed: return "\u{f3d8}"
            case .fabPatreon: return "\u{f3d9}"
            case .fabPaypal: return "\u{f1ed}"
            case .fabPerbyte: return "\u{e083}"
            case .fabPeriscope: return "\u{f3da}"
            case .fabPhabricator: return "\u{f3db}"
            case .fabPhoenixFramework: return "\u{f3dc}"
            case .fabPhoenixSquadron: return "\u{f511}"
            case .fabPhp: return "\u{f457}"
            case .fabPiedPiper: return "\u{f2ae}"
            case .fabPiedPiperAlt: return "\u{f1a8}"
            case .fabPiedPiperHat: return "\u{f4e5}"
            case .fabPiedPiperPp: return "\u{f1a7}"
            case .fabPinterest: return "\u{f0d2}"
            case .fabPinterestP: return "\u{f231}"
            case .fabPix: return "\u{e43a}"
            case .fabPlaystation: return "\u{f3df}"
            case .fabProductHunt: return "\u{f288}"
            case .fabPushed: return "\u{f3e1}"
            case .fabPython: return "\u{f3e2}"
            case .fabQq: return "\u{f1d6}"
            case .fabQuinscape: return "\u{f459}"
            case .fabQuora: return "\u{f2c4}"
            case .fabRProject: return "\u{f4f7}"
            case .fabRaspberryPi: return "\u{f7bb}"
            case .fabRavelry: return "\u{f2d9}"
            case .fabReact: return "\u{f41b}"
            case .fabReacteurope: return "\u{f75d}"
            case .fabReadme: return "\u{f4d5}"
            case .fabRebel: return "\u{f1d0}"
            case .fabRedRiver: return "\u{f3e3}"
            case .fabReddit: return "\u{f1a1}"
            case .fabRedditAlien: return "\u{f281}"
            case .fabRedhat: return "\u{f7bc}"
            case .fabRenren: return "\u{f18b}"
            case .fabReplyd: return "\u{f3e6}"
            case .fabResearchgate: return "\u{f4f8}"
            case .fabResolving: return "\u{f3e7}"
            case .fabRev: return "\u{f5b2}"
            case .fabRocketchat: return "\u{f3e8}"
            case .fabRockrms: return "\u{f3e9}"
            case .fabRust: return "\u{e07a}"
            case .fabSafari: return "\u{f267}"
            case .fabSalesforce: return "\u{f83b}"
            case .fabSass: return "\u{f41e}"
            case .fabSchlix: return "\u{f3ea}"
            case .fabScreenpal: return "\u{e570}"
            case .fabScribd: return "\u{f28a}"
            case .fabSearchengin: return "\u{f3eb}"
            case .fabSellcast: return "\u{f2da}"
            case .fabSellsy: return "\u{f213}"
            case .fabServicestack: return "\u{f3ec}"
            case .fabShirtsinbulk: return "\u{f214}"
            case .fabShopify: return "\u{e057}"
            case .fabShopware: return "\u{f5b5}"
            case .fabSimplybuilt: return "\u{f215}"
            case .fabSistrix: return "\u{f3ee}"
            case .fabSith: return "\u{f512}"
            case .fabSitrox: return "\u{e44a}"
            case .fabSketch: return "\u{f7c6}"
            case .fabSkyatlas: return "\u{f216}"
            case .fabSkype: return "\u{f17e}"
            case .fabSlack: return "\u{f198}"
            case .fabSlideshare: return "\u{f1e7}"
            case .fabSnapchat: return "\u{f2ab}"
            case .fabSoundcloud: return "\u{f1be}"
            case .fabSourcetree: return "\u{f7d3}"
            case .fabSpaceAwesome: return "\u{e5ac}"
            case .fabSpeakap: return "\u{f3f3}"
            case .fabSpeakerDeck: return "\u{f83c}"
            case .fabSpotify: return "\u{f1bc}"
            case .fabSquareBehance: return "\u{f1b5}"
            case .fabSquareDribbble: return "\u{f397}"
            case .fabSquareFacebook: return "\u{f082}"
            case .fabSquareFontAwesome: return "\u{e5ad}"
            case .fabSquareFontAwesomeStroke: return "\u{f35c}"
            case .fabSquareGit: return "\u{f1d2}"
            case .fabSquareGithub: return "\u{f092}"
            case .fabSquareGitlab: return "\u{e5ae}"
            case .fabSquareGooglePlus: return "\u{f0d4}"
            case .fabSquareHackerNews: return "\u{f3af}"
            case .fabSquareInstagram: return "\u{e055}"
            case .fabSquareJs: return "\u{f3b9}"
            case .fabSquareLastfm: return "\u{f203}"
            case .fabSquareOdnoklassniki: return "\u{f264}"
            case .fabSquarePiedPiper: return "\u{e01e}"
            case .fabSquarePinterest: return "\u{f0d3}"
            case .fabSquareReddit: return "\u{f1a2}"
            case .fabSquareSnapchat: return "\u{f2ad}"
            case .fabSquareSteam: return "\u{f1b7}"
            case .fabSquareTumblr: return "\u{f174}"
            case .fabSquareTwitter: return "\u{f081}"
            case .fabSquareViadeo: return "\u{f2aa}"
            case .fabSquareVimeo: return "\u{f194}"
            case .fabSquareWhatsapp: return "\u{f40c}"
            case .fabSquareXing: return "\u{f169}"
            case .fabSquareYoutube: return "\u{f431}"
            case .fabSquarespace: return "\u{f5be}"
            case .fabStackExchange: return "\u{f18d}"
            case .fabStackOverflow: return "\u{f16c}"
            case .fabStackpath: return "\u{f842}"
            case .fabStaylinked: return "\u{f3f5}"
            case .fabSteam: return "\u{f1b6}"
            case .fabSteamSymbol: return "\u{f3f6}"
            case .fabStickerMule: return "\u{f3f7}"
            case .fabStrava: return "\u{f428}"
            case .fabStripe: return "\u{f429}"
            case .fabStripeS: return "\u{f42a}"
            case .fabStubber: return "\u{e5c7}"
            case .fabStudiovinari: return "\u{f3f8}"
            case .fabStumbleupon: return "\u{f1a4}"
            case .fabStumbleuponCircle: return "\u{f1a3}"
            case .fabSuperpowers: return "\u{f2dd}"
            case .fabSupple: return "\u{f3f9}"
            case .fabSuse: return "\u{f7d6}"
            case .fabSwift: return "\u{f8e1}"
            case .fabSymfony: return "\u{f83d}"
            case .fabTeamspeak: return "\u{f4f9}"
            case .fabTelegram: return "\u{f2c6}"
            case .fabTencentWeibo: return "\u{f1d5}"
            case .fabTheRedYeti: return "\u{f69d}"
            case .fabThemeco: return "\u{f5c6}"
            case .fabThemeisle: return "\u{f2b2}"
            case .fabThinkPeaks: return "\u{f731}"
            case .fabTiktok: return "\u{e07b}"
            case .fabTradeFederation: return "\u{f513}"
            case .fabTrello: return "\u{f181}"
            case .fabTumblr: return "\u{f173}"
            case .fabTwitch: return "\u{f1e8}"
            case .fabTwitter: return "\u{f099}"
            case .fabTypo3: return "\u{f42b}"
            case .fabUber: return "\u{f402}"
            case .fabUbuntu: return "\u{f7df}"
            case .fabUikit: return "\u{f403}"
            case .fabUmbraco: return "\u{f8e8}"
            case .fabUncharted: return "\u{e084}"
            case .fabUniregistry: return "\u{f404}"
            case .fabUnity: return "\u{e049}"
            case .fabUnsplash: return "\u{e07c}"
            case .fabUntappd: return "\u{f405}"
            case .fabUps: return "\u{f7e0}"
            case .fabUsb: return "\u{f287}"
            case .fabUsps: return "\u{f7e1}"
            case .fabUssunnah: return "\u{f407}"
            case .fabVaadin: return "\u{f408}"
            case .fabViacoin: return "\u{f237}"
            case .fabViadeo: return "\u{f2a9}"
            case .fabViber: return "\u{f409}"
            case .fabVimeo: return "\u{f40a}"
            case .fabVimeoV: return "\u{f27d}"
            case .fabVine: return "\u{f1ca}"
            case .fabVk: return "\u{f189}"
            case .fabVnv: return "\u{f40b}"
            case .fabVuejs: return "\u{f41f}"
            case .fabWatchmanMonitoring: return "\u{e087}"
            case .fabWaze: return "\u{f83f}"
            case .fabWeebly: return "\u{f5cc}"
            case .fabWeibo: return "\u{f18a}"
            case .fabWeixin: return "\u{f1d7}"
            case .fabWhatsapp: return "\u{f232}"
            case .fabWhmcs: return "\u{f40d}"
            case .fabWikipediaW: return "\u{f266}"
            case .fabWindows: return "\u{f17a}"
            case .fabWirsindhandwerk: return "\u{e2d0}"
            case .fabWix: return "\u{f5cf}"
            case .fabWizardsOfTheCoast: return "\u{f730}"
            case .fabWodu: return "\u{e088}"
            case .fabWolfPackBattalion: return "\u{f514}"
            case .fabWordpress: return "\u{f19a}"
            case .fabWordpressSimple: return "\u{f411}"
            case .fabWpbeginner: return "\u{f297}"
            case .fabWpexplorer: return "\u{f2de}"
            case .fabWpforms: return "\u{f298}"
            case .fabWpressr: return "\u{f3e4}"
            case .fabXbox: return "\u{f412}"
            case .fabXing: return "\u{f168}"
            case .fabYCombinator: return "\u{f23b}"
            case .fabYahoo: return "\u{f19e}"
            case .fabYammer: return "\u{f840}"
            case .fabYandex: return "\u{f413}"
            case .fabYandexInternational: return "\u{f414}"
            case .fabYarn: return "\u{f7e3}"
            case .fabYelp: return "\u{f1e9}"
            case .fabYoast: return "\u{f2b1}"
            case .fabYoutube: return "\u{f167}"
            case .fabZhihu: return "\u{f63f}"

        }
    }
    public var supportedStyles: [FontawesomeBrandsStyle] {
        switch self {
            case .fab42Group: return [.brands]
            case .fab500Px: return [.brands]
            case .fabAccessibleIcon: return [.brands]
            case .fabAccusoft: return [.brands]
            case .fabAdn: return [.brands]
            case .fabAdversal: return [.brands]
            case .fabAffiliatetheme: return [.brands]
            case .fabAirbnb: return [.brands]
            case .fabAlgolia: return [.brands]
            case .fabAlipay: return [.brands]
            case .fabAmazon: return [.brands]
            case .fabAmazonPay: return [.brands]
            case .fabAmilia: return [.brands]
            case .fabAndroid: return [.brands]
            case .fabAngellist: return [.brands]
            case .fabAngrycreative: return [.brands]
            case .fabAngular: return [.brands]
            case .fabAppStore: return [.brands]
            case .fabAppStoreIos: return [.brands]
            case .fabApper: return [.brands]
            case .fabApple: return [.brands]
            case .fabApplePay: return [.brands]
            case .fabArtstation: return [.brands]
            case .fabAsymmetrik: return [.brands]
            case .fabAtlassian: return [.brands]
            case .fabAudible: return [.brands]
            case .fabAutoprefixer: return [.brands]
            case .fabAvianex: return [.brands]
            case .fabAviato: return [.brands]
            case .fabAws: return [.brands]
            case .fabBandcamp: return [.brands]
            case .fabBattleNet: return [.brands]
            case .fabBehance: return [.brands]
            case .fabBilibili: return [.brands]
            case .fabBimobject: return [.brands]
            case .fabBitbucket: return [.brands]
            case .fabBitcoin: return [.brands]
            case .fabBity: return [.brands]
            case .fabBlackTie: return [.brands]
            case .fabBlackberry: return [.brands]
            case .fabBlogger: return [.brands]
            case .fabBloggerB: return [.brands]
            case .fabBluetooth: return [.brands]
            case .fabBluetoothB: return [.brands]
            case .fabBootstrap: return [.brands]
            case .fabBots: return [.brands]
            case .fabBtc: return [.brands]
            case .fabBuffer: return [.brands]
            case .fabBuromobelexperte: return [.brands]
            case .fabBuyNLarge: return [.brands]
            case .fabBuysellads: return [.brands]
            case .fabCanadianMapleLeaf: return [.brands]
            case .fabCcAmazonPay: return [.brands]
            case .fabCcAmex: return [.brands]
            case .fabCcApplePay: return [.brands]
            case .fabCcDinersClub: return [.brands]
            case .fabCcDiscover: return [.brands]
            case .fabCcJcb: return [.brands]
            case .fabCcMastercard: return [.brands]
            case .fabCcPaypal: return [.brands]
            case .fabCcStripe: return [.brands]
            case .fabCcVisa: return [.brands]
            case .fabCentercode: return [.brands]
            case .fabCentos: return [.brands]
            case .fabChrome: return [.brands]
            case .fabChromecast: return [.brands]
            case .fabCloudflare: return [.brands]
            case .fabCloudscale: return [.brands]
            case .fabCloudsmith: return [.brands]
            case .fabCloudversify: return [.brands]
            case .fabCmplid: return [.brands]
            case .fabCodepen: return [.brands]
            case .fabCodiepie: return [.brands]
            case .fabConfluence: return [.brands]
            case .fabConnectdevelop: return [.brands]
            case .fabContao: return [.brands]
            case .fabCottonBureau: return [.brands]
            case .fabCpanel: return [.brands]
            case .fabCreativeCommons: return [.brands]
            case .fabCreativeCommonsBy: return [.brands]
            case .fabCreativeCommonsNc: return [.brands]
            case .fabCreativeCommonsNcEu: return [.brands]
            case .fabCreativeCommonsNcJp: return [.brands]
            case .fabCreativeCommonsNd: return [.brands]
            case .fabCreativeCommonsPd: return [.brands]
            case .fabCreativeCommonsPdAlt: return [.brands]
            case .fabCreativeCommonsRemix: return [.brands]
            case .fabCreativeCommonsSa: return [.brands]
            case .fabCreativeCommonsSampling: return [.brands]
            case .fabCreativeCommonsSamplingPlus: return [.brands]
            case .fabCreativeCommonsShare: return [.brands]
            case .fabCreativeCommonsZero: return [.brands]
            case .fabCriticalRole: return [.brands]
            case .fabCss3: return [.brands]
            case .fabCss3Alt: return [.brands]
            case .fabCuttlefish: return [.brands]
            case .fabDAndD: return [.brands]
            case .fabDAndDBeyond: return [.brands]
            case .fabDailymotion: return [.brands]
            case .fabDashcube: return [.brands]
            case .fabDeezer: return [.brands]
            case .fabDelicious: return [.brands]
            case .fabDeploydog: return [.brands]
            case .fabDeskpro: return [.brands]
            case .fabDev: return [.brands]
            case .fabDeviantart: return [.brands]
            case .fabDhl: return [.brands]
            case .fabDiaspora: return [.brands]
            case .fabDigg: return [.brands]
            case .fabDigitalOcean: return [.brands]
            case .fabDiscord: return [.brands]
            case .fabDiscourse: return [.brands]
            case .fabDochub: return [.brands]
            case .fabDocker: return [.brands]
            case .fabDraft2Digital: return [.brands]
            case .fabDribbble: return [.brands]
            case .fabDropbox: return [.brands]
            case .fabDrupal: return [.brands]
            case .fabDyalog: return [.brands]
            case .fabEarlybirds: return [.brands]
            case .fabEbay: return [.brands]
            case .fabEdge: return [.brands]
            case .fabEdgeLegacy: return [.brands]
            case .fabElementor: return [.brands]
            case .fabEllo: return [.brands]
            case .fabEmber: return [.brands]
            case .fabEmpire: return [.brands]
            case .fabEnvira: return [.brands]
            case .fabErlang: return [.brands]
            case .fabEthereum: return [.brands]
            case .fabEtsy: return [.brands]
            case .fabEvernote: return [.brands]
            case .fabExpeditedssl: return [.brands]
            case .fabFacebook: return [.brands]
            case .fabFacebookF: return [.brands]
            case .fabFacebookMessenger: return [.brands]
            case .fabFantasyFlightGames: return [.brands]
            case .fabFedex: return [.brands]
            case .fabFedora: return [.brands]
            case .fabFigma: return [.brands]
            case .fabFirefox: return [.brands]
            case .fabFirefoxBrowser: return [.brands]
            case .fabFirstOrder: return [.brands]
            case .fabFirstOrderAlt: return [.brands]
            case .fabFirstdraft: return [.brands]
            case .fabFlickr: return [.brands]
            case .fabFlipboard: return [.brands]
            case .fabFly: return [.brands]
            case .fabFontAwesome: return [.brands]
            case .fabFonticons: return [.brands]
            case .fabFonticonsFi: return [.brands]
            case .fabFortAwesome: return [.brands]
            case .fabFortAwesomeAlt: return [.brands]
            case .fabForumbee: return [.brands]
            case .fabFoursquare: return [.brands]
            case .fabFreeCodeCamp: return [.brands]
            case .fabFreebsd: return [.brands]
            case .fabFulcrum: return [.brands]
            case .fabGalacticRepublic: return [.brands]
            case .fabGalacticSenate: return [.brands]
            case .fabGetPocket: return [.brands]
            case .fabGg: return [.brands]
            case .fabGgCircle: return [.brands]
            case .fabGit: return [.brands]
            case .fabGitAlt: return [.brands]
            case .fabGithub: return [.brands]
            case .fabGithubAlt: return [.brands]
            case .fabGitkraken: return [.brands]
            case .fabGitlab: return [.brands]
            case .fabGitter: return [.brands]
            case .fabGlide: return [.brands]
            case .fabGlideG: return [.brands]
            case .fabGofore: return [.brands]
            case .fabGolang: return [.brands]
            case .fabGoodreads: return [.brands]
            case .fabGoodreadsG: return [.brands]
            case .fabGoogle: return [.brands]
            case .fabGoogleDrive: return [.brands]
            case .fabGooglePay: return [.brands]
            case .fabGooglePlay: return [.brands]
            case .fabGooglePlus: return [.brands]
            case .fabGooglePlusG: return [.brands]
            case .fabGoogleWallet: return [.brands]
            case .fabGratipay: return [.brands]
            case .fabGrav: return [.brands]
            case .fabGripfire: return [.brands]
            case .fabGrunt: return [.brands]
            case .fabGuilded: return [.brands]
            case .fabGulp: return [.brands]
            case .fabHackerNews: return [.brands]
            case .fabHackerrank: return [.brands]
            case .fabHashnode: return [.brands]
            case .fabHips: return [.brands]
            case .fabHireAHelper: return [.brands]
            case .fabHive: return [.brands]
            case .fabHooli: return [.brands]
            case .fabHornbill: return [.brands]
            case .fabHotjar: return [.brands]
            case .fabHouzz: return [.brands]
            case .fabHtml5: return [.brands]
            case .fabHubspot: return [.brands]
            case .fabIdeal: return [.brands]
            case .fabImdb: return [.brands]
            case .fabInstagram: return [.brands]
            case .fabInstalod: return [.brands]
            case .fabIntercom: return [.brands]
            case .fabInternetExplorer: return [.brands]
            case .fabInvision: return [.brands]
            case .fabIoxhost: return [.brands]
            case .fabItchIo: return [.brands]
            case .fabItunes: return [.brands]
            case .fabItunesNote: return [.brands]
            case .fabJava: return [.brands]
            case .fabJediOrder: return [.brands]
            case .fabJenkins: return [.brands]
            case .fabJira: return [.brands]
            case .fabJoget: return [.brands]
            case .fabJoomla: return [.brands]
            case .fabJs: return [.brands]
            case .fabJsfiddle: return [.brands]
            case .fabKaggle: return [.brands]
            case .fabKeybase: return [.brands]
            case .fabKeycdn: return [.brands]
            case .fabKickstarter: return [.brands]
            case .fabKickstarterK: return [.brands]
            case .fabKorvue: return [.brands]
            case .fabLaravel: return [.brands]
            case .fabLastfm: return [.brands]
            case .fabLeanpub: return [.brands]
            case .fabLess: return [.brands]
            case .fabLine: return [.brands]
            case .fabLinkedin: return [.brands]
            case .fabLinkedinIn: return [.brands]
            case .fabLinode: return [.brands]
            case .fabLinux: return [.brands]
            case .fabLyft: return [.brands]
            case .fabMagento: return [.brands]
            case .fabMailchimp: return [.brands]
            case .fabMandalorian: return [.brands]
            case .fabMarkdown: return [.brands]
            case .fabMastodon: return [.brands]
            case .fabMaxcdn: return [.brands]
            case .fabMdb: return [.brands]
            case .fabMedapps: return [.brands]
            case .fabMedium: return [.brands]
            case .fabMedrt: return [.brands]
            case .fabMeetup: return [.brands]
            case .fabMegaport: return [.brands]
            case .fabMendeley: return [.brands]
            case .fabMeta: return [.brands]
            case .fabMicroblog: return [.brands]
            case .fabMicrosoft: return [.brands]
            case .fabMix: return [.brands]
            case .fabMixcloud: return [.brands]
            case .fabMixer: return [.brands]
            case .fabMizuni: return [.brands]
            case .fabModx: return [.brands]
            case .fabMonero: return [.brands]
            case .fabNapster: return [.brands]
            case .fabNeos: return [.brands]
            case .fabNfcDirectional: return [.brands]
            case .fabNfcSymbol: return [.brands]
            case .fabNimblr: return [.brands]
            case .fabNode: return [.brands]
            case .fabNodeJs: return [.brands]
            case .fabNpm: return [.brands]
            case .fabNs8: return [.brands]
            case .fabNutritionix: return [.brands]
            case .fabOctopusDeploy: return [.brands]
            case .fabOdnoklassniki: return [.brands]
            case .fabOdysee: return [.brands]
            case .fabOldRepublic: return [.brands]
            case .fabOpencart: return [.brands]
            case .fabOpenid: return [.brands]
            case .fabOpera: return [.brands]
            case .fabOptinMonster: return [.brands]
            case .fabOrcid: return [.brands]
            case .fabOsi: return [.brands]
            case .fabPadlet: return [.brands]
            case .fabPage4: return [.brands]
            case .fabPagelines: return [.brands]
            case .fabPalfed: return [.brands]
            case .fabPatreon: return [.brands]
            case .fabPaypal: return [.brands]
            case .fabPerbyte: return [.brands]
            case .fabPeriscope: return [.brands]
            case .fabPhabricator: return [.brands]
            case .fabPhoenixFramework: return [.brands]
            case .fabPhoenixSquadron: return [.brands]
            case .fabPhp: return [.brands]
            case .fabPiedPiper: return [.brands]
            case .fabPiedPiperAlt: return [.brands]
            case .fabPiedPiperHat: return [.brands]
            case .fabPiedPiperPp: return [.brands]
            case .fabPinterest: return [.brands]
            case .fabPinterestP: return [.brands]
            case .fabPix: return [.brands]
            case .fabPlaystation: return [.brands]
            case .fabProductHunt: return [.brands]
            case .fabPushed: return [.brands]
            case .fabPython: return [.brands]
            case .fabQq: return [.brands]
            case .fabQuinscape: return [.brands]
            case .fabQuora: return [.brands]
            case .fabRProject: return [.brands]
            case .fabRaspberryPi: return [.brands]
            case .fabRavelry: return [.brands]
            case .fabReact: return [.brands]
            case .fabReacteurope: return [.brands]
            case .fabReadme: return [.brands]
            case .fabRebel: return [.brands]
            case .fabRedRiver: return [.brands]
            case .fabReddit: return [.brands]
            case .fabRedditAlien: return [.brands]
            case .fabRedhat: return [.brands]
            case .fabRenren: return [.brands]
            case .fabReplyd: return [.brands]
            case .fabResearchgate: return [.brands]
            case .fabResolving: return [.brands]
            case .fabRev: return [.brands]
            case .fabRocketchat: return [.brands]
            case .fabRockrms: return [.brands]
            case .fabRust: return [.brands]
            case .fabSafari: return [.brands]
            case .fabSalesforce: return [.brands]
            case .fabSass: return [.brands]
            case .fabSchlix: return [.brands]
            case .fabScreenpal: return [.brands]
            case .fabScribd: return [.brands]
            case .fabSearchengin: return [.brands]
            case .fabSellcast: return [.brands]
            case .fabSellsy: return [.brands]
            case .fabServicestack: return [.brands]
            case .fabShirtsinbulk: return [.brands]
            case .fabShopify: return [.brands]
            case .fabShopware: return [.brands]
            case .fabSimplybuilt: return [.brands]
            case .fabSistrix: return [.brands]
            case .fabSith: return [.brands]
            case .fabSitrox: return [.brands]
            case .fabSketch: return [.brands]
            case .fabSkyatlas: return [.brands]
            case .fabSkype: return [.brands]
            case .fabSlack: return [.brands]
            case .fabSlideshare: return [.brands]
            case .fabSnapchat: return [.brands]
            case .fabSoundcloud: return [.brands]
            case .fabSourcetree: return [.brands]
            case .fabSpaceAwesome: return [.brands]
            case .fabSpeakap: return [.brands]
            case .fabSpeakerDeck: return [.brands]
            case .fabSpotify: return [.brands]
            case .fabSquareBehance: return [.brands]
            case .fabSquareDribbble: return [.brands]
            case .fabSquareFacebook: return [.brands]
            case .fabSquareFontAwesome: return [.brands]
            case .fabSquareFontAwesomeStroke: return [.brands]
            case .fabSquareGit: return [.brands]
            case .fabSquareGithub: return [.brands]
            case .fabSquareGitlab: return [.brands]
            case .fabSquareGooglePlus: return [.brands]
            case .fabSquareHackerNews: return [.brands]
            case .fabSquareInstagram: return [.brands]
            case .fabSquareJs: return [.brands]
            case .fabSquareLastfm: return [.brands]
            case .fabSquareOdnoklassniki: return [.brands]
            case .fabSquarePiedPiper: return [.brands]
            case .fabSquarePinterest: return [.brands]
            case .fabSquareReddit: return [.brands]
            case .fabSquareSnapchat: return [.brands]
            case .fabSquareSteam: return [.brands]
            case .fabSquareTumblr: return [.brands]
            case .fabSquareTwitter: return [.brands]
            case .fabSquareViadeo: return [.brands]
            case .fabSquareVimeo: return [.brands]
            case .fabSquareWhatsapp: return [.brands]
            case .fabSquareXing: return [.brands]
            case .fabSquareYoutube: return [.brands]
            case .fabSquarespace: return [.brands]
            case .fabStackExchange: return [.brands]
            case .fabStackOverflow: return [.brands]
            case .fabStackpath: return [.brands]
            case .fabStaylinked: return [.brands]
            case .fabSteam: return [.brands]
            case .fabSteamSymbol: return [.brands]
            case .fabStickerMule: return [.brands]
            case .fabStrava: return [.brands]
            case .fabStripe: return [.brands]
            case .fabStripeS: return [.brands]
            case .fabStubber: return [.brands]
            case .fabStudiovinari: return [.brands]
            case .fabStumbleupon: return [.brands]
            case .fabStumbleuponCircle: return [.brands]
            case .fabSuperpowers: return [.brands]
            case .fabSupple: return [.brands]
            case .fabSuse: return [.brands]
            case .fabSwift: return [.brands]
            case .fabSymfony: return [.brands]
            case .fabTeamspeak: return [.brands]
            case .fabTelegram: return [.brands]
            case .fabTencentWeibo: return [.brands]
            case .fabTheRedYeti: return [.brands]
            case .fabThemeco: return [.brands]
            case .fabThemeisle: return [.brands]
            case .fabThinkPeaks: return [.brands]
            case .fabTiktok: return [.brands]
            case .fabTradeFederation: return [.brands]
            case .fabTrello: return [.brands]
            case .fabTumblr: return [.brands]
            case .fabTwitch: return [.brands]
            case .fabTwitter: return [.brands]
            case .fabTypo3: return [.brands]
            case .fabUber: return [.brands]
            case .fabUbuntu: return [.brands]
            case .fabUikit: return [.brands]
            case .fabUmbraco: return [.brands]
            case .fabUncharted: return [.brands]
            case .fabUniregistry: return [.brands]
            case .fabUnity: return [.brands]
            case .fabUnsplash: return [.brands]
            case .fabUntappd: return [.brands]
            case .fabUps: return [.brands]
            case .fabUsb: return [.brands]
            case .fabUsps: return [.brands]
            case .fabUssunnah: return [.brands]
            case .fabVaadin: return [.brands]
            case .fabViacoin: return [.brands]
            case .fabViadeo: return [.brands]
            case .fabViber: return [.brands]
            case .fabVimeo: return [.brands]
            case .fabVimeoV: return [.brands]
            case .fabVine: return [.brands]
            case .fabVk: return [.brands]
            case .fabVnv: return [.brands]
            case .fabVuejs: return [.brands]
            case .fabWatchmanMonitoring: return [.brands]
            case .fabWaze: return [.brands]
            case .fabWeebly: return [.brands]
            case .fabWeibo: return [.brands]
            case .fabWeixin: return [.brands]
            case .fabWhatsapp: return [.brands]
            case .fabWhmcs: return [.brands]
            case .fabWikipediaW: return [.brands]
            case .fabWindows: return [.brands]
            case .fabWirsindhandwerk: return [.brands]
            case .fabWix: return [.brands]
            case .fabWizardsOfTheCoast: return [.brands]
            case .fabWodu: return [.brands]
            case .fabWolfPackBattalion: return [.brands]
            case .fabWordpress: return [.brands]
            case .fabWordpressSimple: return [.brands]
            case .fabWpbeginner: return [.brands]
            case .fabWpexplorer: return [.brands]
            case .fabWpforms: return [.brands]
            case .fabWpressr: return [.brands]
            case .fabXbox: return [.brands]
            case .fabXing: return [.brands]
            case .fabYCombinator: return [.brands]
            case .fabYahoo: return [.brands]
            case .fabYammer: return [.brands]
            case .fabYandex: return [.brands]
            case .fabYandexInternational: return [.brands]
            case .fabYarn: return [.brands]
            case .fabYelp: return [.brands]
            case .fabYoast: return [.brands]
            case .fabYoutube: return [.brands]
            case .fabZhihu: return [.brands]

        }
    }
}